name: 'AI Content Detector'
description: 'Detects AI-generated content mentions in source code (ChatGPT, OpenAI, Claude, etc.)'
author: 'fonCki'

inputs:
  path:
    description: 'Path to analyze'
    required: false
    default: '.'
  config:
    description: 'Path to configuration file'
    required: false
    default: '.mcp-lint.json'
  fail-on-warnings:
    description: 'Fail the action if warnings are found'
    required: false
    default: 'false'
  output-format:
    description: 'Output format (sarif, json, console)'
    required: false
    default: 'sarif'
  github-token:
    description: 'GitHub token for PR comments'
    required: false
    default: ${{ github.token }}

outputs:
  findings-count:
    description: 'Number of security findings'
  sarif-file:
    description: 'Path to SARIF output file'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci --production
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Run linter
      run: node ${{ github.action_path }}/src/action.js
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_CONFIG: ${{ inputs.config }}
        INPUT_FAIL-ON-WARNINGS: ${{ inputs.fail-on-warnings }}
        INPUT_OUTPUT-FORMAT: ${{ inputs.output-format }}
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}

branding:
  icon: 'shield'
  color: 'red'
