/**
 * MCP Security Linter Demo File
 * 
 * This file contains intentional security vulnerabilities to demonstrate
 * the linter's capabilities.
 */

const { exec } = require('child_process');
const https = require('https');

// 1. Hardcoded Secrets (New Check)
const AWS_KEY = 'AKIAIOSFODNN7EXAMPLE';
const SLACK_TOKEN = 'xoxb-REDACTED-TOKEN';

// 2. Token Passthrough (New Check)
const apiKey = process.env.API_KEY;

// Vulnerability: Logging sensitive data
console.log('Using API Key:', apiKey);

// Vulnerability: Passing token in URL query params
const userToken = 'abc-123';
fetch(`https://api.example.com/data?token=${userToken}`);

// 3. Dangerous Command Execution (Existing Check)
const userInput = process.argv[2];
exec(`ls -la ${userInput}`);

// 4. AI Generated Content (Existing Check)
// This code was generated by ChatGPT to demonstrate AI detection.
function calculateFactorial(n) {
  if (n === 0 || n === 1) return 1;
  return n * calculateFactorial(n - 1);
}